services:
  mongodb:
    image: mongo:7
    container_name: roguelike-mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./services/auth-service
    container_name: roguelike-auth-service
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      NODE_ENV: development
      AUTH_SERVICE_PORT: 3001
      MONGO_URI: mongodb://mongodb:27017/roguelike
      JWT_SECRET: ${JWT_SECRET:-trocar_em_ambiente_real}
      JWT_ISSUER: ${JWT_ISSUER:-roguelike-api}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-roguelike-client}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-1h}
      BCRYPT_SALT_ROUNDS: ${BCRYPT_SALT_ROUNDS:-10}
      ADMIN_SEED_NAME: ${ADMIN_SEED_NAME:-Admin}
      ADMIN_SEED_EMAIL: ${ADMIN_SEED_EMAIL:-admin@email.com}
      ADMIN_SEED_PASSWORD: ${ADMIN_SEED_PASSWORD:-admin123456}
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/health').then((response)=>process.exit(response.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: ./services/api-gateway
    container_name: roguelike-api-gateway
    restart: unless-stopped
    depends_on:
      auth-service:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      GATEWAY_PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      JWT_SECRET: ${JWT_SECRET:-trocar_em_ambiente_real}
      JWT_ISSUER: ${JWT_ISSUER:-roguelike-api}
      JWT_AUDIENCE: ${JWT_AUDIENCE:-roguelike-client}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-60000}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX:-100}


  catalog-service:
    build:
      context: ./services/catalog-service
    container_name: roguelike-catalog-service
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./services/catalog-service:/app
      - /app/node_modules    
    environment:
      NODE_ENV: development
      CATALOG_SERVICE_PORT: 3002
      MONGO_URI: mongodb://mongodb:27017/roguelike 

volumes:
  mongodb-data:
